Updated docs to show python 3.9+ requirement
azimuth-cloud/azimuth-config pull request #130
Opened 2024-03-21 15:08 UTC by Chris-green-stfc

Running Ubuntu 20.04, with python version 3.8, meaning that python features are lacking for azimuth install process. Update docs to make this clear.

2024-03-21 17:04 UTC, mkjpryor commented
@Chris-green-stfc

#128 merged yesterday that causes `ensure-venv` to error out unless `python3` is 3.9+. Is that sufficient?

2024-03-22 10:08 UTC, Chris-green-stfc commented
I think it is good the mention it in the docs as well, just so people know before hand

2024-03-22 11:36 UTC, mkjpryor requested changes

2024-03-22 11:36 UTC, mkjpryor commented on docs/deployment/index.md
> +In the configuration directory and install the required dependencies:
Revert this change, and instead add a `!!! warning` under the code block instead, i.e.:

```
!!! warning

    Azimuth requires Python 3.9 or newer.
```

This way, it will be more attention-grabbing.

2024-12-03 12:00 UTC, closed without merging