Document using K9s on the seed
azimuth-cloud/azimuth-config pull request #159
Opened 2024-07-08 12:26 UTC by MoteHue

2024-07-08 17:00 UTC, mkjpryor requested changes
This is pretty close - you just need to add the page to the index before it will appear in the rendered output.

2024-07-08 17:00 UTC, mkjpryor commented on docs/debugging/using-k9s.md
> +K9s is installed onto the seed VM. You can use this for a more interractive
Typo - "interractive"

2024-07-08 17:00 UTC, mkjpryor commented on docs/debugging/using-k9s.md
> +ubuntu@azimuth-staging-seed:~$ export KUBECONFIG=./kubeconfig-azimuth-staging.yaml
Use generic names as in the "accessing the HA cluster page" I think?

2024-07-12 14:57 UTC, MoteHue commented on docs/debugging/using-k9s.md
> +ubuntu@azimuth-staging-seed:~$ export KUBECONFIG=./kubeconfig-azimuth-staging.yaml
What do you mean by this? This is the same command as in "Accessing the HA cluster"

2024-07-12 14:57 UTC, MoteHue commented on docs/debugging/using-k9s.md
> +K9s is installed onto the seed VM. You can use this for a more interractive
done

2025-03-21 09:25 UTC, JohnGarbutt commented on docs/debugging/using-k9s.md
> +ubuntu@azimuth-staging-seed:~$ export KUBECONFIG=./kubeconfig-azimuth-staging.yaml
Yeah, I think this is good.

2025-03-21 09:25 UTC, JohnGarbutt approved these changes

2025-03-21 09:26 UTC, merged