Add strong recommendation for portal-external tag
azimuth-cloud/azimuth-config pull request #181
Opened 2024-10-15 12:58 UTC by MoteHue

2024-10-15 13:12 UTC, mkjpryor requested changes

2024-10-15 13:12 UTC, mkjpryor commented on docs/configuration/04-target-cloud.md
> +
Maybe even make this a tip, so it is visually different?

2024-10-15 15:17 UTC, MoteHue commented on docs/configuration/04-target-cloud.md
> +
Done

2024-10-16 09:08 UTC, mkjpryor approved these changes
LGTM

2024-10-16 09:08 UTC, merged